In [2]:
import numpy as np
from scipy import linalg
from scipy.stats import ortho_group

Придумайте матрицы, которые обладают следующими свойствами:

a) диагональная, ортогональная, но не единичная(!):

b) верхнетреугольная, ортогональная:

c) нижнетреугольная, ортогональная: 

d) матрица, у которой определитель = 1, и все элементы не равны 0:

e) матрица (3x3), у которой определитель = 1:

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

a)

In [29]:
m = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, -1]])
det = np.linalg.det(m)
print(m)
print(det)

[[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
-1.0


b)

In [23]:
m = np.triu([[1,1,1],[1,1,1],[1,1,1]])
det = np.linalg.det(m)
print(m)
print(det)

[[1 1 1]
 [0 1 1]
 [0 0 1]]
1.0


c)

In [24]:
m = np.tril([[1,1,1],[1,1,1],[1,1,1]])
det = np.linalg.det(m)
print(m)
print(det)

[[1 0 0]
 [1 1 0]
 [1 1 1]]
1.0


d)

In [28]:
m = np.array([[1, 2], [1, 3]])
det = np.linalg.det(m)
print(m)
print(det)

[[1 2]
 [1 3]]
1.0


e)

In [43]:
m = np.array([[1, 1, 1], [1, 2, 1], [1, 1, 2]])
det = np.linalg.det(m)
print(m)
print(det)

[[1 1 1]
 [1 2 1]
 [1 1 2]]
1.0


Найдите собственные значения и собственные вектора матриц

In [47]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [48]:
w, v = np.linalg.eig(m)

In [49]:
for i in range(len(w)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]
